spring.application.name=conference

spring.datasource.url=jdbc:postgresql://localhost:5432/freepass
spring.datasource.username=alex
spring.datasource.password=alex

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

security.jwt.secret-key=aefe508c98b2236b62beb9f73ac3322eda7497315f3d73afaf3205d8edd76ad4
security.jwt.token-expiration=86400000